[package]
name = "shine-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
tokio = { version = "1", features = ["full"] }
askama = "0.16.0"
tower-http = { version = "0.7.0", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
typst = "0.15.1"
typst-layout = "0.15.1"
typst-pdf = "0.15.1"
fontdb = "0.24.0"
base64 = "0.23.1"
uuid = { version = "1", features = ["v4"] }
